swagger: "2.0"
info:
  title: Qr code generator api
  description: This api can return an svg QR-code for the data it receives.
  version: 1.0.0
host: qrcodeservice.herokuapp.com
basePath: /
schemes:
  - https
paths:
  /:
    get:
      summary: Returns a qr-code based on the url-params provided
      description: Optional extended description in Markdown.
      produces:
        - image/svg+xml
      parameters:
        - in: query
          name: query
          type: string
          required: true
          description: data to be encoded in the qr-code
        - in: query
          name: version
          type: integer
          required: false
          description: "The version parameter is an integer from 1 to 40 that controls the size of the QR Code (the smallest, version 1, is a 21x21 matrix). Don't include this parameter when making the code to determine this automatically."
        - in: query
          name: error_correction
          type: integer
          required: false
          description: "The ``error_correction`` parameter controls the error correction used for the
            QR Code. The following four constants are made available on the ``qrcode``
            package:

            ``1``:
            About 7% or less errors can be corrected.

            ``0`` (default):
            About 15% or less errors can be corrected.

            ``3``:
            About 25% or less errors can be corrected.

            ``2``:
            About 30% or less errors can be corrected."
        - in: query
          name: box_size
          type: integer
          required: false
          description: "The ``box_size`` parameter controls how many pixels each \"box\" of the QR code is."
        - in: query
          name: border
          type: integer
          required: false
          description: "The ``border`` parameter controls how many boxes thick the border should be (the default is 4, which is the minimum according to the specs)."
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        500:
          description: Internal server error / Malformed query variable